baseURL = 'https://stephenredding.com/'
languageCode = 'en-us'
title = 'Stephen Redding'
canonifyURLs = true

[params]
css = "css/tailwind.css"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
